package com.example.blinkitadmin

object Constants {

    val allProductCategory = arrayOf(
        "All",
        "Vegetables & Fruits",
        "Atta, Rice & Dal",
        "Oil, Ghee & Masala",
        "Dairy, Bread & Eggs",
        "Bakery & Biscuits",
        "Dry Fruits & Cereals",
        "Chicken, Meat & Fish",
        "Kitchenware & Appliances",
        "Chips & Namkeen",
        "Sweets & Chocolates",
        "Drinks & Juices",
        "Tea, Coffee & Milk Drinks",
        "Instant Food",
        "Sauces & Spreads",
        "Paan Corner",
        "Ice Creams & More",
        "Bath & Body",
        "Hair",
        "Skin & Face",
        "Beauty & Cosmetics",
        "Feminine Hygiene",
        "Baby Care",
        "Health & Pharma",
        "Sexual Wellness",
        "Home & Lifestyle",
        "Cleaners & Repellents",
        "Electronics",
        "Stationery & Games"
    )

    val allUnitsOfProducts = arrayOf(
        "Kg",
        "gm",
        "Ltr",
        "ml",
        "packet",
        "piece",
        "dozen"
    )

    val allProductTypes = arrayOf(
        "Vegetables",
        "Fruits",
        "Atta",
        "Rice",
        "Dal",
        "Oil",
        "Ghee",
        "Masala",
        "Dairy",
        "Bread",
        "Eggs",
        "Bakery",
        "Biscuits",
        "Dry Fruits",
        "Cereals",
        "Chicken",
        "Meat",
        "Fish",
        "Kitchenware",
        "Kitchen Appliances",
        "Chips",
        "Namkeen",
        "Sweets",
        "Chocolates",
        "Drinks",
        "Juices",
        "Tea",
        "Coffee",
        "Milk Drinks",
        "Instant Food",
        "Sauces",
        "Spreads",
        "Paan",
        "Hookah",
        "Lighter",
        "Tobacco",
        "Ice Creams",
        "Soap",
        "Shampoo",
        "Body Wash",
        "Moisturizer",
        "Hair Oil",
        "Conditioners",
        "Face Creams",
        "Cosmetics",
        "Feminine Hygiene",
        "Baby Care",
        "Health & Pharma",
        "Sexual Wellness",
        "Home & Lifestyle",
        "Cleaners",
        "Repellents",
        "Electronics",
        "Stationery",
        "Games"
    )

}